### ISSUE TITLE
Use offsets to query in chunks

### ISSUE THREAD

**Issue by dlamblin** [blue-yonder/bonfire#21]
I seem to get too many logs OR the client doesn't use chunks:
```
$ bonfire -h our-log.server.net -u login -k -t -f -@'1 second ago' application:airflow
Please select a stream to query:
0: Stream 'All' (id: 586b17d304e6a30001fb4559)
Enter stream number: [0]: 
Traceback (most recent call last):
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/bin/bonfire", line 11, in <module>
    sys.exit(run())
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/bonfire/cli.py", line 196, in run
    run_logprint(gl_api, q, formatter, follow, interval, latency, output)
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/bonfire/output.py", line 23, in run_logprint
    result = run_logprint(api, query, formatter, follow=False, output=output)
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/bonfire/output.py", line 35, in run_logprint
    result = api.search(query, fetch_all=True)
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/bonfire/output.py", line 35, in run_logprint
    result = api.search(query, fetch_all=True)
  File "/Users/daniellamblin/VEnvs/pythonToolsEnv/lib/python2.7/site-packages/bonfire/graylog_api.py", line 125, in search
    raise RuntimeError("Query returns more than 10000 log entries. Use offsets to query in chunks.")
RuntimeError: Query returns more than 10000 log entries. Use offsets to query in chunks.
```

This would be related to the used of the `-f` flag; Without it the command would return 10 lines, and without `-t` and a more generous `-@` it seems to work correctly.

**Comment by valentin-krasontovitsch** [comment]
duplciate of #27 (or vice versa), closing for now.
